# Dockerfile: transmission
# Kafouche Transmission Image (source).

ARG         RELEASE=4.0.6

ARG         SOURCE_URL=https://github.com/transmission/transmission/releases/download/$RELEASE/transmission-$RELEASE.tar.xz

ARG         SOURCE_DIR=/tmp/source

ARG         SOURCE_TAR=/tmp/archive.tar.xz

ARG         TARGET_DIR=/tmp/target


# BUILD STAGE

FROM        ghcr.io/kafouche/alpine:latest as buildstage

ARG         SOURCE_DIR \
            SOURCE_TAR \
            SOURCE_URL \
            TARGET_DIR

RUN         apk --no-cache --update upgrade \
            && apk --no-cache --update add \
              clang \
              cmake \
              curl-dev \
              gettext-dev \
              gtest-dev \
              linux-headers \
              openssl-dev \
              patch \
              samurai

RUN         apk --no-cache --update add \
              libdeflate-dev \
              libevent-dev \
              libnatpmp-dev \
              libpsl-dev \
              miniupnpc-dev

COPY        miniupnpc.patch /tmp/

RUN         apk --no-cache --update add \
                curl \
            && curl \
              --location "${SOURCE_URL}" \
              --output "${SOURCE_TAR}" \
            && mkdir --parents "${SOURCE_DIR}" \
            && tar \
              --directory="${SOURCE_DIR}" \
              --extract \
              --file="${SOURCE_TAR}" \
              --xz \
              --strip-components=1 \
            && patch --directory="${SOURCE_DIR}/libtransmission/" < /tmp/miniupnpc.patch

WORKDIR     "${SOURCE_DIR}"

RUN         cmake -B build -G Ninja \
              -DBUILD_SHARED_LIBS=OFF \
              -DCMAKE_BUILD_TYPE=None \
              -DCMAKE_INSTALL_PREFIX=/usr \
              -DCMAKE_INSTALL_LIBDIR=lib \
              -DENABLE_DEPRECATED=ON \
              -DENABLE_CLI=OFF \
              -DENABLE_GTK=OFF \
              -DENABLE_NLS=OFF \
              -DENABLE_QT=OFF \
              -DENABLE_TESTS=ON \
              -DUSE_SYSTEM_DEFLATE=ON \
              -DUSE_SYSTEM_EVENT2=ON \
              -DUSE_SYSTEM_MINIUPNPC=ON \
              -DUSE_SYSTEM_PSL=ON \
              -DWITH_CRYPTO="openssl" \
              -DWITH_SYSTEMD=OFF \
            && cmake --build build \
            && ctest --test-dir build --output-on-failure -j4 -E LT.DhtTest.usesBootstrapFile \
            && DESTDIR="${TARGET_DIR}" cmake --install build

# RUN STAGE

FROM        ghcr.io/kafouche/alpine:latest

LABEL       org.opencontainers.image.authors="kafouche"
LABEL       org.opencontainers.image.base.name="ghcr.io/kafouche/transmission:4.0.6"
LABEL       org.opencontainers.image.ref.name="ghcr.io/kafouche/alpine"
LABEL       org.opencontainers.image.source="https://github.com/kafouche/container-transmission"
LABEL       org.opencontainers.image.title="Transmission BitTorrent"
LABEL       org.opencontainers.image.version="4.0.6"
LABEL       image.tags[0]="ghcr.io/kafouche/transmission:latest-src"

# ------------------------------------------------------------------------------

ARG         TARGET_DIR

RUN         apk --no-cache --update upgrade \
            && apk --no-cache --update add \
              libcurl \
              libdeflate \
              libevent \
              libnatpmp \
              libpsl \
              libstdc++ \
              miniupnpc

RUN         mkdir --parents /var/lib/transmission/{config,downloads}

COPY        --from=buildstage "${TARGET_DIR}/" /
COPY        settings.json /var/lib/transmission/config/

RUN         addgroup -S transmission \
            && adduser -D -G transmission -h /var/lib/transmission -H -s /sbin/nologin -S transmission \
            && chown -R transmission:transmission /var/lib/transmission/ \
            && chmod 644 /var/lib/transmission/config/settings.json

VOLUME      /var/lib/transmission/config \
            /var/lib/transmission/downloads

WORKDIR     /var/lib/transmission

EXPOSE      9091/tcp \
            51413/tcp \
            51413/udp

USER        transmission

ENTRYPOINT  [ \
              "/usr/bin/transmission-daemon", \
              "--config-dir", "/var/lib/transmission/config", \
              "--download-dir", "/var/lib/transmission/downloads", \
              "--foreground" \
            ]
